// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNsSqnOfN3tdR6tO9VoLpBQ5nQKxZxD94',
    appId: '1:143631754060:web:003960638183f491b525e9',
    messagingSenderId: '143631754060',
    projectId: 'citizenscience-ffb5c',
    authDomain: 'citizenscience-ffb5c.firebaseapp.com',
    storageBucket: 'citizenscience-ffb5c.appspot.com',
    measurementId: 'G-1HGC8MDZV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpp9q8HB3nteD8zcijgCZ2NBzDljteII',
    appId: '1:143631754060:android:435cb11d0b45362fb525e9',
    messagingSenderId: '143631754060',
    projectId: 'citizenscience-ffb5c',
    storageBucket: 'citizenscience-ffb5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZhT_Bwr4XH4DP3Tw12o5xX1hrCPGs-I',
    appId: '1:143631754060:ios:b81eb0bc8f19007ab525e9',
    messagingSenderId: '143631754060',
    projectId: 'citizenscience-ffb5c',
    storageBucket: 'citizenscience-ffb5c.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZhT_Bwr4XH4DP3Tw12o5xX1hrCPGs-I',
    appId: '1:143631754060:ios:b81eb0bc8f19007ab525e9',
    messagingSenderId: '143631754060',
    projectId: 'citizenscience-ffb5c',
    storageBucket: 'citizenscience-ffb5c.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNsSqnOfN3tdR6tO9VoLpBQ5nQKxZxD94',
    appId: '1:143631754060:web:003960638183f491b525e9',
    messagingSenderId: '143631754060',
    projectId: 'citizenscience-ffb5c',
    authDomain: 'citizenscience-ffb5c.firebaseapp.com',
    storageBucket: 'citizenscience-ffb5c.appspot.com',
    measurementId: 'G-1HGC8MDZV5',
  );
}
